// Generated by CoffeeScript 1.6.3
(function() {
  var Client, client;

  process.stdout.write('\u001B[2J\u001B[0;0f');

  Client = require('..').Client;

  client = new Client({
    verbose: true,
    browser: {
      verbose: true
    }
  });

  client.on('ready', function() {
    var _this = this;
    console.log('ready');
    return setTimeout((function() {
      return _this.goto('');
    }), 3000);
  });

}).call(this);
